# Generated by Django 5.1.8 on 2025-06-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastseason',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voxpopseason',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
