# Generated by Django 5.1.8 on 2025-05-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voxpopepisode',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
