# Generated by Django 5.1.8 on 2025-07-13 04:23

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_podcastseason_is_archived_voxpopseason_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='thumbnail',
            field=utils.fields.SecureImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='voxpopepisode',
            name='thumbnail',
            field=utils.fields.SecureImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
