# Generated by Django 5.1.8 on 2025-06-05 08:57

import apps.common.models
import apps.news.models
import django.db.models.deletion
import django_choices_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='News Title')),
                ('description', models.TextField(verbose_name='News Description')),
                ('published_date', models.DateTimeField(verbose_name='News Published Date')),
                ('status', django_choices_field.fields.IntegerChoicesField(choices=[(101, 'Draft'), (102, 'Published')], choices_enum=apps.common.models.StatusEnum, default=101)),
                ('news_type', django_choices_field.fields.IntegerChoicesField(choices=[(100, 'News'), (200, 'Other Update')], choices_enum=apps.news.models.NewsTypeEnum, default=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
