# Generated by Django 5.1.8 on 2025-09-01 08:33

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='cover_image',
            field=utils.fields.SecureImageField(blank=True, null=True, upload_to='news_cover_image/', verbose_name='News Cover Image'),
        ),
    ]
