# Generated by Django 5.1.6 on 2025-04-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=232, verbose_name='Title')),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('author', models.CharField(max_length=232, verbose_name='Author')),
                ('description', models.CharField(verbose_name='Description')),
                ('cover_image', models.ImageField(upload_to='blogs/', verbose_name='Cover Image')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
            ],
        ),
    ]
