# Generated by Django 5.1.8 on 2025-06-14 10:59

import apps.common.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(50, 'Draft'), (60, 'Published'), (70, 'Archived')], choices_enum=apps.common.models.StatusEnum, default=50),
        ),
    ]
