# Generated by Django 5.1.8 on 2025-07-13 04:23

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=utils.fields.SecureImageField(blank=True, null=True, upload_to='author/', verbose_name='Author Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=utils.fields.SecureImageField(upload_to='blogs/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='blogasset',
            name='file',
            field=utils.fields.SecureFileField(upload_to='', verbose_name='File'),
        ),
    ]
