# Generated by Django 5.1.8 on 2025-05-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_cover_image',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, null=True, verbose_name='Location'),
        ),
    ]
