# Generated by Django 5.1.8 on 2025-06-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cover_image',
            field=models.ImageField(default='', upload_to='report_cover_image/', verbose_name='Report File'),
            preserve_default=False,
        ),
    ]
