# Generated by Django 5.1.8 on 2025-07-13 04:23

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_report_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=utils.fields.SecureImageField(upload_to='artwork_images/'),
        ),
        migrations.AlterField(
            model_name='eventasset',
            name='image',
            field=utils.fields.SecureImageField(upload_to='', verbose_name='Event Images'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=utils.fields.SecureImageField(upload_to='gallery_images/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cover_image',
            field=utils.fields.SecureImageField(upload_to='report_cover_image/', verbose_name='Report File'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=utils.fields.SecureFileField(upload_to='reports/', verbose_name='Report File'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='thumbnail',
            field=utils.fields.SecureImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
