# Generated by Django 5.1.8 on 2025-06-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_galleryitem_youtubevideo_delete_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='release_date',
            field=models.DateTimeField(verbose_name=' Video Release Date'),
        ),
    ]
