# Generated by Django 5.1.8 on 2025-07-22 07:49

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=utils.fields.SecureImageField(blank=True, null=True, upload_to='event-thumbnails/'),
        ),
    ]
