# Generated by Django 5.1.8 on 2025-09-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_changemaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='changemaker',
            name='website_link',
            field=models.URLField(blank=True, null=True, verbose_name='Website Link'),
        ),
    ]
