# Generated by Django 5.1.8 on 2025-07-13 04:23

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_photo',
            field=utils.fields.SecureImageField(blank=True, null=True, upload_to='member_photos/'),
        ),
    ]
