# Generated by Django 5.1.8 on 2025-07-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teammember_bio_alter_teammember_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
