# Generated by Django 5.1.8 on 2025-08-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_teammember_facebook_link_teammember_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['member_order', 'first_name']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='member_order',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Member order'),
        ),
    ]
