apiVersion: v2
name: capn-website-backend-helm
description: "Helm Chart to deploy the CAPN Website Backend"
type: application
version: 0.0.1-SET-BY-CICD
sources:
  - https://github.com/capn-nepal/website-backend/

dependencies:
  - name: toggle-django-helm
    alias: app
    version: 0.2.0
    repository: oci://ghcr.io/toggle-corp
