app:
  environment: Alpha
  image:
    name: ghcr.io/capn-nepal/website-backend
    tag: latest

  ingress:
    host: api.example.com

  postgresql:
    primary:
      persistence:
        storageClass: my-storage-class

  minio:
    global:
      defaultStorageClass: my-storage-class
    apiIngress:
      hostname: minio.example.com
    auth:
      rootPassword: very-secure-password

  # NOTE: Check main/settings.py for all available options
  env:
    # AWS
    AWS_S3_ENABLED: "true"
    AWS_S3_ENDPOINT_URL: "https://capn.minio.com"
    AWS_S3_STATIC_BUCKET_NAME: "static-data"
    AWS_S3_MEDIA_BUCKET_NAME: "media-data"
    # App Domain
    SESSION_COOKIE_DOMAIN: .test.com
    CSRF_COOKIE_DOMAIN: .test.com
    APP_TYPE: "WEB"

  # NOTE: Check main/settings.py for all available options
  secrets:
    DJANGO_SECRET_KEY: very-secret-key
    # Postgres
    POSTGRES_DB: "test"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "test"
    POSTGRES_HOST: "test"
    POSTGRES_PORT: "test"
    # Minio (S3)
    AWS_S3_ACCESS_KEY_ID: "test"
    AWS_S3_SECRET_ACCESS_KEY: "test"
    AWS_S3_REGION: "us-east-1"
    # Misc
    SENTRY_DSN: "https://test.com"
